### PR TITLE
added support to enter recovery mode from the script

### PR DESCRIPTION
**Pull request by JoeyEamigh**

### CODE REVIEW

**Comment by raspberryenvoie** [comment]
Hello, I don't own any A11 device. So could you tell me what happens we when you use the auto recovery mode feature with it?
Thanks :)

**Comment by JoeyEamigh** [comment]
For some reason on A11 iOS 14.2 with AutoRecovery mode feature on, as the device enters pwnDFU mode the script will not notice and instead send it back to recovery mode. I honestly think it is a bug on Apple's end, and the Pi's lsusb doesn't show DFU mode anymore while checkm8 is executing. This is a working theory but nonetheless the -r flag that I added to your script as well as the recovery mode button in the web app are useful simply for putting your phone quickly into recovery mode. It also sets the ENV back to autoboot as you can see so it doesn't loop into recovery mode. It is not the most necessary feature but has really improved my quality of life so that I do not have to manually enter recovery mode to jailbreak. Thank you!

**Comment by raspberryenvoie** [comment]
Okay, I understand what you mean.
Why don't you set the sleep time to 4 in the `piRa1n` file? My iPhone sometimes takes 4-5 seconds to enter recovery mode. I believe that would be better.

**Comment by JoeyEamigh** [comment]
I wasn't fully sure how long it would take to enter a state where the phone is ready to accept ENV variables. Feel free to make any adjustments to the script as you see fit. It was mostly so that I could use PiRa1n-web to put my phone in recovery.

**Comment by raspberryenvoie** [comment]
Thank you for your PR
Have a nice day :)

**Pull request merged**
